// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWnV84AHFS4SG8nElT1bUFpu-rrg2n16Q',
    appId: '1:714001076404:web:811a2afb35cbe2f10bc7e1',
    messagingSenderId: '714001076404',
    projectId: 'evently-47470',
    authDomain: 'evently-47470.firebaseapp.com',
    storageBucket: 'evently-47470.firebasestorage.app',
    measurementId: 'G-Z4L9SD5C7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjQjL1kFBMcUc7kptdFH7RluFjq1GCvJg',
    appId: '1:714001076404:android:ff471aadf9d1c8000bc7e1',
    messagingSenderId: '714001076404',
    projectId: 'evently-47470',
    storageBucket: 'evently-47470.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTOmgEUYGoVqbha_DSIxzWewR5qC0uNjI',
    appId: '1:714001076404:ios:6d02ff4d279bca5e0bc7e1',
    messagingSenderId: '714001076404',
    projectId: 'evently-47470',
    storageBucket: 'evently-47470.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTOmgEUYGoVqbha_DSIxzWewR5qC0uNjI',
    appId: '1:714001076404:ios:6d02ff4d279bca5e0bc7e1',
    messagingSenderId: '714001076404',
    projectId: 'evently-47470',
    storageBucket: 'evently-47470.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWnV84AHFS4SG8nElT1bUFpu-rrg2n16Q',
    appId: '1:714001076404:web:802946b8ed1c04370bc7e1',
    messagingSenderId: '714001076404',
    projectId: 'evently-47470',
    authDomain: 'evently-47470.firebaseapp.com',
    storageBucket: 'evently-47470.firebasestorage.app',
    measurementId: 'G-XB9X8NMKXW',
  );
}
